### ISSUE TITLE
Compile rete

### ISSUE THREAD

**Issue by emanuelperpetuo** [retejs/rete#323]
How to compile retejs?

**Comment by Ni55aN** [comment]
For which environment? For web it has js bundles that generated using rete-cli (rollup). Commands in package.json

**Comment by emanuelperpetuo** [comment]
I try to modify retejs because a need to include some functions like this project https://github.com/projectstorm/react-diagrams. I install ubuntu for windows 10, and execute this comands: npm install, npm rebuild and npm run build, but I get some errors like this: 

npm run build

> rete@1.3.1-rc.3 prebuild /mnt/d/Flipfloplab/Projetos/ReteJS/rete
> npm run lint & npm test && npm run types


> rete@1.3.1-rc.3 lint /mnt/d/Flipfloplab/Projetos/ReteJS/rete
> tsc && eslint --ext .ts --ext .js src


> rete@1.3.1-rc.3 test /mnt/d/Flipfloplab/Projetos/ReteJS/rete
> BABEL_ENV=test mocha -r ts-node/register test/**.ts


/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/view/node.ts:103:40 - error TS2326: Types of property 'prev' are incompatible.
  Type 'number[]' is missing the following properties from type '[number, number]': 0, 1

103         this.trigger('nodetranslated', { node, prev });
                                           ~~~~~~~~~~~~~~

    at createTSError (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:245:12)
    at reportTSError (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:249:19)
    at getOutput (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:362:34)
    at Object.compile (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:395:32)
    at Module.m._compile (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:473:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/src/view/index.ts:8:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/src/editor.ts:5:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/src/index.ts:8:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/test/control.ts:1:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/mnt/d/Flipfloplab/Projetos/ReteJS/rete/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! Test failed.  See above for more details.

npm ERR! Linux 4.4.0-17134-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! rete@1.3.1-rc.3 prebuild: `npm run lint & npm test && npm run types`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rete@1.3.1-rc.3 prebuild script 'npm run lint & npm test && npm run types'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rete package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint & npm test && npm run types
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rete
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rete
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/d/Flipfloplab/Projetos/ReteJS/rete/npm-debug.log
emanuelperpetuo@DESKTOP-59CTMIN:/mnt/d/Flipfloplab/Projetos/ReteJS/rete$ src/view/node.ts:103:40 - error TS2326: Types of property 'prev' are incompatible.
  Type 'number[]' is missing the following properties from type '[number, number]': 0, 1

103         this.trigger('nodetranslated', { node, prev });
                                           ~~~~~~~~~~~~~~


Found 1 error.


npm ERR! Linux 4.4.0-17134-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "lint"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! rete@1.3.1-rc.3 lint: `tsc && eslint --ext .ts --ext .js src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rete@1.3.1-rc.3 lint script 'tsc && eslint --ext .ts --ext .js src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rete package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && eslint --ext .ts --ext .js src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rete
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rete
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/d/Flipfloplab/Projetos/ReteJS/rete/npm-debug.log

what I make wrong?

**Comment by Ni55aN** [comment]
> Types of property 'prev' are incompatible.
Type 'number[]' is missing the following properties from type '[number, number]

**Comment by Ni55aN** [comment]
Are you sure you need to modify the code of this package? You can fork and support it independently, but you cannot get the latest changes of the official package.

**Comment by emanuelperpetuo** [comment]
I'm going to study the code to see if I can put the modifications into a new plugin.  I need some features that have in this project(https://github.com/projectstorm/react-diagrams) how to select it with the mouse, and modify the connections that are really cool.  what do you suggest?

**Comment by emanuelperpetuo** [comment]
Today I use rete version 1.0.0, where I found change log to the last version?

**Comment by Ni55aN** [comment]
> where I found change log to the last version?

In commits of this repo and related plugins

**Comment by Ni55aN** [comment]
>  into a new plugin

https://rete.js.org/#/cli#lang=en&tosearch=Plugin%20creation

> how to select it with the mouse, and modify the connections that are really cool. what do you suggest?

I dont understand. What exactly do you need?

**Comment by emanuelperpetuo** [comment]
I would like to implement these functions in the editor (select the nodes with the mouse, clicking and dragging, copy and paste, modify the connection lines, etc) like in this example that I showed you. Do you think I can do all this with plugins? As for the complication, version 1.0 I can compile, but 1.3.1-rc.3 I can not ... what steps and what do I need to have installed to compile version 1.3.1-rc.3?

**Comment by Ni55aN** [comment]
You do not need to compile all of these packages, as they are published in NPM

>  modify the connection lines

Try `rete-path-reroute-plugin`

**Comment by emanuelperpetuo** [comment]
how to fix this error?:

TSError: ⨯ Unable to compile TypeScript:
src/view/node.ts:103:40 - error TS2326: Types of property 'prev' are incompatible.
  Type 'number[]' is missing the following properties from type '[number, number]': 0, 1

103         this.trigger('nodetranslated', { node, prev });

**Comment by emanuelperpetuo** [comment]
I fixed, my problem is node version... I instaled node 10 , now it works

**Comment by Ni55aN** [comment]
What version did you have installed?

**Comment by emanuelperpetuo** [comment]
v1.3.1-rc.3

**Comment by Ni55aN** [comment]
I mean node.js version

**Comment by emanuelperpetuo** [comment]
I was with 8, this was giving problem ... with 10 everything ok

**Comment by Ni55aN** [comment]
I have built it successfully using Node v8.16.0

**Comment by emanuelperpetuo** [comment]
My old version was 8.0.3 ...
