### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by jezell** [retejs/rete#400]
git cloned repo, did npm install, ran npm run build, get lots of errors. Is there a different build process?

```
> rete@1.4.2 lint /rete
> tsc && eslint --ext .ts --ext .js src


/rete/node_modules/ts-node/src/index.ts:240
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.js:1:1 - error TS1208: Cannot compile namespaces when the '--isolatedModules' flag is provided.

1 "use strict";
  ~~~~~~~~~~~~

    at createTSError (/rete/node_modules/ts-node/src/index.ts:240:12)
    at reportTSError (/rete/node_modules/ts-node/src/index.ts:244:19)
    at getOutput (/rete/node_modules/ts-node/src/index.ts:360:34)

```

**Comment by Ni55aN** [comment]
Cannot reproduce on Ubuntu 18.04.2
Node.js v12.14.1
NPM v6.13.4
